worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    upstream sitanfu {
        server backend:8000;
    }

    server {
        listen 80;

        # 代理 Django 应用
        location / {
            proxy_pass http://sitanfu;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 访问存储文件
        location /storage/ {
            alias /app/environment/frontend_server/storage;
            access_log off;
            expires 30d;
        }

        location /compressed_storage/ {
            alias /app/environment/frontend_server/compressed_storage;
            access_log off;
            expires 30d;
        }
    }
}