"""
Django settings for frontend_server project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ROOT_DIR = os.path.dirname(os.path.dirname(BASE_DIR))

# print(BASE_DIR)
# print(ROOT_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c7l%1%b=2sh$o9zqvd4i*h8*__^@-5sm-y)m(1ib2t92)43@62'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne', # 必须在channels的上面
    'channels', # 用于WebSocket
    'translator',
    'corsheaders',
    'storages',
    'rest_framework', 
    'drf_yasg',  # 必须添加 
    'django.contrib.staticfiles',   # 必须启用 
] 

MIDDLEWARE = [
    # 安全相关中间件优先 
    'django.middleware.security.SecurityMiddleware', 

    # CORS中间件必须紧接安全中间件之后 
    'corsheaders.middleware.CorsMiddleware',   # ← 关键位置 

    # 后续中间件按功能顺序排列 
    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.middleware.common.CommonMiddleware', 
    # 'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
]

ROOT_URLCONF = 'frontend_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'frontend_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_root")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_dirs"),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media_root")


# CORS_ORIGIN_WHITELIST = [
# 'http://127.0.0.1:8080'
# ]

CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOW_CREDENTIALS = False


# 实验存储配置 
EXPERIMENT_STORAGE_ROOT = os.path.join(BASE_DIR,  'storage')
# 实验存储模版配置
EXPERIMENT_TEMPLATES_STORAGE_ROOT = os.path.join(BASE_DIR,  'temp_storage')
 
# 公共实验白名单 
PUBLIC_EXPERIMENT_WHITELIST = [
    # 基础模板系列 
    'base_the_ville_isabella_maria_klaus',
    'base_the_ville_n25',
    'base_the_ville_smol_elections_5_voters',
    'base_the_ville_smol_elections_5_voters_swapped_personalities',

    # July标准实验序列 
    'July1_the_ville_isabella_maria_klaus-step-3-1',
    'July1_the_ville_isabella_maria_klaus-step-3-2',
    'July1_the_ville_isabella_maria_klaus-step-3-3',
    'July1_the_ville_isabella_maria_klaus-step-3-4',
    'July1_the_ville_isabella_maria_klaus-step-3-5',
    'July1_the_ville_isabella_maria_klaus-step-3-6',
    'July1_the_ville_isabella_maria_klaus-step-3-7',
    'July1_the_ville_isabella_maria_klaus-step-3-8',
    'July1_the_ville_isabella_maria_klaus-step-3-9',
    'July1_the_ville_isabella_maria_klaus-step-3-10',
    'July1_the_ville_isabella_maria_klaus-step-3-11',
    'July1_the_ville_isabella_maria_klaus-step-3-12',
    'July1_the_ville_isabella_maria_klaus-step-3-13',
    'July1_the_ville_isabella_maria_klaus-step-3-14',
    'July1_the_ville_isabella_maria_klaus-step-3-15',
    'July1_the_ville_isabella_maria_klaus-step-3-16',
    'July1_the_ville_isabella_maria_klaus-step-3-17',
    'July1_the_ville_isabella_maria_klaus-step-3-18',
    'July1_the_ville_isabella_maria_klaus-step-3-19',
    'July1_the_ville_isabella_maria_klaus-step-3-20',
    'July1_the_ville_isabella_maria_klaus-step-3-21',

    # 跳过夜晚的实验
    'skip-morning-s-14'
]

#添加缓存配置示例
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 
        'LOCATION': 'experiment-cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}
X_FRAME_OPTIONS = 'ALLOWALL'


# WebSocket
ASGI_APPLICATION = 'frontend_server.asgi.application'

